services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 0d000721
    ports:
      - "172.31.241.156:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - booth-network
    restart: always

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-server
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=0d000721
      - NACOS_AUTH_TOKEN=dGFtYWthcmF0YW1ha2FyYXRhbWFrYXJhdGFtYWthcmE=
      - NACOS_AUTH_IDENTITY_KEY=root
      - NACOS_AUTH_IDENTITY_VALUE=0d000721
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "172.31.241.156:8080:8080"
      - "172.31.241.156:8848:8848"
      - "172.31.241.156:9848:9848"
    depends_on:
      - mysql
    volumes:
      - nacos-data:/home/nacos/data
    networks:
      - booth-network
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "172.31.241.156:9000:9000"
      - "172.31.241.156:9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 0d000721
    volumes:
      - minio_data:/data
    networks:
      - booth-network
    restart: always
    command: server /data --console-address ":9001"

volumes:
  mysql-data:
  nacos-data:
  minio_data:

networks:
  booth-network:
    driver: bridge
