spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 172.31.241.156:8848
    openfeign:
      okhttp:
        enabled: true
  datasource:
    url: jdbc:mysql://172.31.241.156:3306/user_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user_service_user
    password: 0d000721
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081


mybatis-plus:
  type-aliases-package: com.bakabooth.user.domain.entity
  mapper-locations: "classpath*:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null

wx:
  appid: wxe0aa3b765aa7bc5c
  secret: 4305ba8944eb90a520842bc500f67480